In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
path = list(files.upload().keys())[0]

Saving jobs.csv to jobs.csv

In [ ]:
df = pd.read_csv(path)

In [ ]:
df.head()

        Company Name                Location                    Job Title
0  Commonwealth Bank  Sydney Area, Australia          Portfolio Executive
1  Commonwealth Bank  Sydney Area, Australia  Solution Delivery Executive
2            CommSec  Sydney Area, Australia              Project Manager
3  Commonwealth Bank  Sydney Area, Australia              Project Manager
4             PayPal  Sydney Area, Australia     Senior Marketing Manager

In [ ]:
df.shape

(39537, 3)

In [ ]:
df = df.sample(5000 , ignore_index = True)

In [ ]:
import string

In [ ]:
panch = string.punctuation
panch

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def remove_panch(text):
  mylist = []
  for i in text.split():
    if i not in panch:
      mylist.append(i)
  return " ".join(mylist)

In [ ]:
df['Job Title'] = df['Job Title'].apply(remove_panch)

In [ ]:
df['Location'] = df['Location'].apply(remove_panch)

In [ ]:
# df['Company Name'] = df['Company Name'].apply(remove_panch)   #this code shows error because string method will not apply on float data .

In [ ]:
df['Company Name'] = df['Company Name'].astype(str)

In [ ]:
df['Company Name'] = df['Company Name'].apply(remove_panch)

In [ ]:
df['Content'] = df.apply(lambda x :" ".join(x.dropna().astype(str)) , axis=1)

In [ ]:
df

,Company Name,Location,Job Title,Content
0,MAX Solutions,"Brisbane, Australia",Information Systems Manager (National),"MAX Solutions Brisbane, Australia Information ..."
1,McCullough Robertson,"Brisbane, Australia",Senior Associate,"McCullough Robertson Brisbane, Australia Senio..."
2,South Australian Cricket Association,"Adelaide, Australia",Legal Counsel,"South Australian Cricket Association Adelaide,..."
3,Engine Room Apps Pty Ltd,"Perth, Australia",Director of Development Projects,"Engine Room Apps Pty Ltd Perth, Australia Dire..."
4,Bates Smart,"Sydney, Australia",Interior Designer,"Bates Smart Sydney, Australia Interior Designer"
...,...,...,...,...
4995,WMC Resources,"Adelaide, Australia",Electrical Engineer,"WMC Resources Adelaide, Australia Electrical E..."
4996,City Beach Australia,"Woolloomooloo, New South Wales, Australia",Visual Merchandiser,"City Beach Australia Woolloomooloo, New South ..."
4997,NCS Group,"Melbourne, Australia",Senior SAP HR Consultant,"NCS Group Melbourne, Australia Senior SAP HR C..."
4998,Two Kites Project,"Sydney, Australia",President,"Two Kites Project Sydney, Australia President"
4999,Turner Townsend Thinc,"Brisbane, Queensland, Australia",Consultant,"Turner Townsend Thinc Brisbane, Queensland, Au..."

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features = 5000)

In [ ]:
metrics = cv.fit_transform(df['Content']).toarray()

In [ ]:
metrics.shape

(5000, 5000)

In [ ]:
similarity = cosine_similarity(metrics)

In [ ]:
def recommend(Job_Title):
  index = df[df['Job Title'] == Job_Title].index[0]
  distances = sorted(list(enumerate(similarity[index])),reverse = True , key = lambda x:x[1])
  new_index = [i[0] for i in distances[1:11]]
  return df.iloc[new_index , :-1]

In [ ]:
df.sample(5)

,Company Name,Location,Job Title,Content
2800,Nokia,"Sydney, Australia",NPO Project Manager,"Nokia Sydney, Australia NPO Project Manager"
3110,Hays,"New South Wales, Australia",Recruitment Consultant,"Hays New South Wales, Australia Recruitment Co..."
4966,Oracle,"Sydney, Australia",Solution Director,"Oracle Sydney, Australia Solution Director"
1766,HR Coach Australasia,"Townsville, Australia",Network Member,"HR Coach Australasia Townsville, Australia Net..."
4439,Spot Image,"Sydney Area, Australia",Part Time Technical Development Manager,"Spot Image Sydney Area, Australia Part Time Te..."

In [ ]:
recommend('Interior Designer')

,Company Name,Location,Job Title
4467,GroupGSA,"Sydney Area, Australia",Interior Designer
4514,ATP Innovations,"Sydney, Australia",Interior Designer
411,Haycom,"Sydney, Australia",Exhibition Designer
525,TBWA\Australia,"Sydney, Australia",Integrated designer
1205,PMDL Architecture Design,"Sydney Area, Australia",Interior Designer
1563,Virtu,"Sydney, Australia",Graphic Designer
4107,UNSW,"Sydney, Australia",Graphic Designer
4706,Nearmap,"Sydney, Australia",UX Designer
2172,Morphos Group,"Sydney Area, Australia",Project Coordinator Interior Designer
954,Atlassian,"Sydney Area, Australia",Graduate Designer

In [ ]:
recommend('Senior Associate')

,Company Name,Location,Job Title
641,Clayton Utz,"Brisbane, Australia",Senior Associate
1680,HopgoodGanim Lawyers,"Brisbane, Australia",Senior Associate
4135,McCullough Robertson,"Brisbane, Australia",Lawyer (Commercial)
4431,Kemp Strang,"Brisbane, Australia",Senior Associate
3007,Warlow Scott,"Brisbane, Australia",Senior Solicitor; Associate Insurance
1197,Ash St.,"Brisbane, Australia",Associate
1317,HASSELL,"Sydney, Australia",Senior Associate
1931,Ashurst,"Sydney, Australia",Senior Associate
2415,PwC,"Adelaide, Australia",Senior Associate
3298,Gadens,"Sydney, Australia",Senior Associate

In [ ]:
recommend('Solution Director')

            Company Name                Location         Job Title
792        ThunderMetric       Sydney, Australia          Director
1024            COGiTATE       Sydney, Australia          Director
1284   Balmain Guarantee       Sydney, Australia          Director
1896           Capgemini       Sydney, Australia          Director
634   Ensemble Australia       Sydney, Australia  Account Director
2954        UM Australia       Sydney, Australia    Group Director
3946          PMI Sydney  Sydney Area, Australia          Director
124                 LOUD       Sydney, Australia    Group Director
200              Westpac       Sydney, Australia  Project Director
202         Grant Samuel       Sydney, Australia          Director